import Link from "next/link";

const LAST_UPDATED = "May 10, 2026";

const SECTIONS = [
  {
    title: "What BigEmailDaddy is",
    body: [
      "BigEmailDaddy is a cold email tool that helps university students write and send personalised outreach emails to professors, researchers, and recruiters.",
      "We use information from your resume, GitHub profile, and target research to generate email drafts. You review and send them. We are a writing and delivery tool — not an email marketing or spam platform.",
    ],
  },
  {
    title: "Acceptable use",
    body: [
      "You may only use BigEmailDaddy to send emails that you have personally reviewed and approved. Automated bulk sending is not permitted.",
      "You may not use BigEmailDaddy to send spam, unsolicited commercial email, phishing messages, or any content that is illegal, harassing, or deceptive.",
      "You are responsible for the content of every email sent from your account. BigEmailDaddy generates drafts — you send them.",
      "You must be at least 16 years old to use this service.",
    ],
  },
  {
    title: "Your account",
    body: [
      "You sign in with your Google account. You are responsible for keeping your account secure.",
      "We reserve the right to suspend or terminate accounts that violate these terms, are used for spam, or are inactive for more than 12 months.",
      "You can delete your account at any time by emailing bigemaildad@gmail.com.",
    ],
  },
  {
    title: "Payments and refunds",
    body: [
      "BigEmailDaddy is a subscription service at $30 USD per month. You can cancel at any time — no questions asked.",
      "Cancellation takes effect at the end of your current billing period. We do not offer partial refunds for unused time.",
      "If you experience a technical issue that prevents you from using the service, contact us at bigemaildad@gmail.com and we will assess refunds on a case-by-case basis.",
    ],
  },
  {
    title: "Intellectual property",
    body: [
      "The emails generated by BigEmailDaddy are yours. We make no claim to content you create or send using the platform.",
      "The BigEmailDaddy platform, codebase, and branding are owned by us. You may not copy, resell, or reverse-engineer the service.",
    ],
  },
  {
    title: "Limitation of liability",
    body: [
      "BigEmailDaddy is provided as-is. We do not guarantee that emails sent through the platform will receive replies, result in interviews, or achieve any particular outcome.",
      "We are not liable for any indirect, incidental, or consequential damages arising from your use of the service.",
      "Our total liability to you for any claim is limited to the amount you paid us in the 30 days prior to the claim.",
    ],
  },
  {
    title: "Changes to these terms",
    body: [
      "We may update these terms from time to time. If we make material changes, we will notify you by email or by displaying a notice in the app.",
      "Continued use of BigEmailDaddy after changes are posted constitutes acceptance of the updated terms.",
    ],
  },
  {
    title: "Contact",
    body: [
      "Questions about these terms? Email bigemaildad@gmail.com.",
    ],
  },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#faf8f4] px-6 py-16">
      <div className="mx-auto max-w-2xl">
        <Link
          href="/"
          className="mb-12 inline-block text-[11px] uppercase tracking-widest text-[#9ca3af] transition-colors hover:text-[#111010]"
          style={{ fontFamily: "var(--font-mono), monospace" }}
        >
          ← Back
        </Link>

        <h1
          className="mt-6 text-[36px] font-black tracking-tight text-[#111010]"
          style={{ fontFamily: "var(--font-serif), serif" }}
        >
          Terms of Service
        </h1>
        <p
          className="mt-2 text-[12px] text-[#9ca3af]"
          style={{ fontFamily: "var(--font-mono), monospace" }}
        >
          Last updated: {LAST_UPDATED}
        </p>

        <p className="mt-6 text-[14px] leading-relaxed text-[#6b7280]">
          By using BigEmailDaddy, you agree to these terms. We&apos;ve kept them
          short and in plain English.
        </p>

        <div className="mt-12 space-y-10">
          {SECTIONS.map(({ title, body }) => (
            <div key={title}>
              <h2
                className="text-[18px] font-bold text-[#111010]"
                style={{ fontFamily: "var(--font-serif), serif" }}
              >
                {title}
              </h2>
              <div className="mt-3 space-y-3">
                {body.map((para) => (
                  <p
                    key={para}
                    className="text-[14px] leading-relaxed text-[#4b5563]"
                  >
                    {para}
                  </p>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}
